# Generated by Django 4.1.2 on 2022-12-01 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoEvento', models.CharField(choices=[('CUL', 'Evento Cultural'), ('ACA', 'Evento Academico'), ('PEDA', 'Evento Pedagogico'), ('RECRE', 'Evento Recreativo')], default='CUL', max_length=20, verbose_name='Tipo de Evento')),
                ('nombreEve', models.CharField(max_length=60, verbose_name='Nombre del evento')),
                ('descripEve', models.CharField(max_length=100, verbose_name='Descripción del evento')),
                ('fechaEve', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha del Evento')),
                ('horaEve', models.TimeField(help_text='00:00:00', verbose_name='Hora del Evento')),
                ('lugarEve', models.CharField(max_length=60, verbose_name='Lugar del Evento')),
                ('encagEve', models.CharField(max_length=60, verbose_name='Encargados del Evento')),
                ('duracionEve', models.CharField(max_length=60, verbose_name='Duración del Evento')),
                ('invitados', models.CharField(max_length=60, verbose_name='Invitados al Evento')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
