# Generated by Django 4.1.2 on 2022-12-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.CharField(choices=[('CULTURAL', 'Evento Cultural'), ('ACADÉMICO', 'Evento Académico'), ('PEDAGÓGICO', 'Evento Pedagógico'), ('INFORMATIVO', 'Evento Informativo')], default='CULTURAL', max_length=20, verbose_name='Tipo de Evento')),
                ('nombreEve', models.CharField(max_length=60, verbose_name='Nombre del evento')),
                ('descripEve', models.TextField(max_length=10000, verbose_name='Descripción del evento')),
                ('fechaEve', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha del Evento')),
                ('horaEve', models.TimeField(blank=True, help_text='00:00:00', null=True, verbose_name='Hora del Evento')),
                ('lugarEve', models.CharField(blank=True, max_length=60, null=True, verbose_name='Lugar del Evento')),
                ('encagEve', models.CharField(blank=True, max_length=60, null=True, verbose_name='Encargados del Evento')),
                ('duracionEve', models.CharField(blank=True, max_length=60, null=True, verbose_name='Duración del Evento')),
                ('invitados', models.CharField(blank=True, max_length=60, null=True, verbose_name='Invitados al Evento')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('foto', models.ImageField(blank=True, default='images/eventos/default.jpg', upload_to='images/eventos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
