# Generated by Django 4.1.1 on 2022-10-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDoc', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de Documento')),
                ('numDoc', models.CharField(max_length=60, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('Jornada', models.CharField(choices=[('MAÑANA', 'Jornada Mañana'), ('TARDE', 'Jornada Tarde')], default='MAÑANA', max_length=10, verbose_name='Jornada')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=40, verbose_name='Dirección')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo Electrónico')),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indefinido')], default='M', max_length=3, verbose_name='Género')),
                ('Rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECTIVO', 'Directivo'), ('SECRETARIA', 'Secretaria')], default='ADMIN', max_length=10, verbose_name='Rol')),
                ('Estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
