# Generated by Django 4.1.2 on 2022-12-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preregistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDoc', models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('NES', 'Número de Secretaria'), ('PP', 'Pasaporte')], default='RC', max_length=6, verbose_name='Tipo de Documento')),
                ('numDoc', models.CharField(max_length=60, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('jornadaInt', models.CharField(choices=[('MAÑANA', 'Jornada Mañana'), ('TARDE', 'Jornada Tarde')], default='MAÑANA', max_length=10, verbose_name='Jornada que le interesa')),
                ('gradoInt', models.CharField(choices=[('6', 'Grado Sexto'), ('7', 'Grado Séptimo'), ('8', 'Grado Octavo'), ('9', 'Grado Noveno'), ('10', 'Grado Décimo')], default='6', max_length=5, verbose_name='Grado que le interesa')),
                ('direccion', models.CharField(max_length=40, verbose_name='Dirección')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo Electrónico')),
                ('tipoDocAcu', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de Documento del Acudiente')),
                ('numDocAcu', models.CharField(max_length=60, verbose_name='Número de Documento del Acudiente')),
                ('nombresAcu', models.CharField(max_length=60, verbose_name='Nombres del Acudiente')),
                ('apellidosAcu', models.CharField(max_length=60, verbose_name='Apellidos del Acudiente')),
                ('telefonoAcu', models.CharField(max_length=20, verbose_name='Teléfono del Acudiente')),
                ('correoAcu', models.CharField(max_length=40, verbose_name='Correo Electrónico del Acudiente')),
                ('colProce', models.CharField(max_length=60, verbose_name='Colegio de Porecedencia')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
