# Generated by Django 4.1.2 on 2022-12-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('docentes', '0001_initial'),
        ('grado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPublicacion', models.CharField(choices=[('INFORMATIVA', 'Publicación Informativa'), ('ACADÉMICA', 'Publicación Academica'), ('CULTURAL', 'Publicación Cultural'), ('PEDAGOGICA', 'Publicación Pedagógica')], default='CULTURAL', max_length=20, verbose_name='Tipo de Publicacion')),
                ('nombrePubli', models.CharField(max_length=60, verbose_name='Nombre de la Publicación')),
                ('descripPublic', models.CharField(max_length=100, verbose_name='Descripción de la Publicación')),
                ('linkPubli', models.CharField(blank=True, max_length=80, verbose_name='Link de la Publicación')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('jornada', models.CharField(blank=True, choices=[('MAÑANA', 'Jornada Mañana'), ('TARDE', 'Jornada Tarde')], default='MAÑANA', max_length=10, verbose_name='Jornada')),
                ('docente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='docentes.docente', verbose_name='Docente')),
                ('grado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='grado.grado', verbose_name='Grado')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
