# Generated by Django 4.1.1 on 2022-10-18 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('grado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del Tipo de Publicación')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la publicación')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePubli', models.CharField(max_length=60, verbose_name='Nombre de la Publicación')),
                ('descripPublic', models.CharField(max_length=60, verbose_name='Descripción de la Publicación')),
                ('linkPubli', models.CharField(max_length=60, verbose_name='Link de la Publicación')),
                ('Estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('Jornada', models.CharField(choices=[('MAÑANA', 'Jornada Mañana'), ('TARDE', 'Jornada Tarde')], default='MAÑANA', max_length=10, verbose_name='Jornada')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.docente', verbose_name='Docente')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grado.grado', verbose_name='Grado')),
                ('tipoPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.tipopublicacion', verbose_name='Tipo de Publicación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
