# Generated by Django 4.1.1 on 2022-11-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='tipoPublicacion',
        ),
        migrations.DeleteModel(
            name='TipoPublicacion',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='TipoPublicacion',
            field=models.CharField(choices=[('INF', 'Publicacion Informativa'), ('ACA', 'Publicacion Academica'), ('CUL', 'Publicacion Cultural'), ('PEDA', 'Publicacion Pedagodica')], default='CUL', max_length=20, verbose_name='Tipo de Publicacion'),
        ),
    ]
