# Generated by Django 4.1.2 on 2022-12-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('grado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='numGrado',
        ),
        migrations.AlterField(
            model_name='grado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
    ]
