# Generated by Django 4.1.2 on 2022-12-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0002_remove_grado_numgrado_alter_grado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nomGrado',
            field=models.CharField(max_length=60, verbose_name='Nombre Grado'),
        ),
    ]
